### ISSUE TITLE
Devops project using Docker

### ISSUE THREAD

**Issue by 0904-mansi** [collabnix/community#53]
/assign

**Comment by ajeetraina** [comment]
Hi @0904-mansi Can you list out the topic that you want to contribute to?

**Comment by 0904-mansi** [comment]
> Hi @0904-mansi Can you list out the topic that you want to contribute to?

Hello @ajeetraina sir! Yes sir

**Comment by 0904-mansi** [comment]
I want to contribute to Docker, Jenkins, Kubernetes, sub tools like kubectl , docker hub etc.. @ajeetraina  sir I have a doubt that I have to add only a project idea or complete project to this repo?

**Comment by ajeetraina** [comment]
Let me give you an example:

I worked on a project called Pico https://github.com/collabnix/pico
Pico is all about Object detection and analytics using Docker, AWS Cloud & IoT.
Now this is how I will get it added to the community site:

1. Raise an issue 
2. As this project is targeted at Docker as tool and IoT as category, I will first create "IoT" under Docker
3. Create a child-page called "Pico" and then add instructions and README under that.

Other Examples:

https://community.collabnix.com/docs/docker/jenkins/

**Comment by 0904-mansi** [comment]
> Let me give you an example:
> 
> I worked on a project called Pico https://github.com/collabnix/pico Pico is all about Object detection and analytics using Docker, AWS Cloud & IoT. Now this is how I will get it added to the community site:
> 
>     1. Raise an issue
> 
>     2. As this project is targeted at Docker as tool and IoT as category, I will first create "IoT" under Docker
> 
>     3. Create a child-page called "Pico" and then add instructions and README under that.
> 
> 
> Other Examples:
> 
> https://community.collabnix.com/docs/docker/jenkins/

ok sir

**Comment by ajeetraina** [comment]
@0904-mansi Put all the stuff in doc and I will help you add it to the community site

**Comment by 0904-mansi** [comment]
> @0904-mansi Put all the stuff in doc and I will help you add it to the community site
Ok sir, is there any time limit?

**Comment by ajeetraina** [comment]
There is no time limit.

**Comment by 0904-mansi** [comment]
> There is no time limit.

ok because I have my colleges from 10 to 5 pm🥲

**Comment by ajeetraina** [comment]
Important notes:
1. Rather than just creating README.md file, it is recommended to create _index.md file
2. Don't directly create a directory under docker. Click on "Create Child Page" on the right hand side of the page
3. The _index.md has certain structure that needs to be followed.

**Comment by yeofrancis** [comment]
do I continue here for GitLab?
